name: CI

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test:
    name: Node.js v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16, 17]
    steps:
      - uses: actions/checkout@main

      - name: (env) setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0-beta.2

      - name: (env) setup node v${{ matrix.node }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          check-latest: true

      - name: Install
        run: pnpm install

      - name: Compiles
        run: pnpm run build

      - name: Test
        run: pnpm test

      - name: Check Types
        run: pnpm run typecheck
